
ArmorList = [
'Bronze Armor',
'Dragon Armor',
'Pad Armor',
'Legendary Armor',
'Bone Armor',
'Leather Armor',
'Scale Armor',
'Sphinx Armor',
'Brass Armor',
'Plate Armor',
'Vine Armor',
'Silk Armor',
'Wind Armor',
'Spirit Armor',
'Guardian Armor',
'Storm Crow Armor',
'Black Dragon Armor',
'Dark Phoenix Armor',
'Grand Sould Armor',
'HolySpirit Armor',
'Thunder Armor',
'Great Dragon Armor',
'Black Soul Armor',
'Hurricane Armor',
'Red Spirit Armor',
'Round Armor',
'Adamantine Armor',
'Dark Steel Armor',
'Dark Master Armor',
'Dragon Knight Armor',
'Venomist Armor',
'Sylpid Ray Armor',
'Volcano Armor',
'Sunlight Armor',
'Ashcrow Armor',
'Eclipse Armor',
'Iris Armor',
'Valiant Armor',
'Glorious Armor',
'Mistery Armor',
'Red wing Armor',
'Ancient Armor',
'Black Rose Armor',
'Aura Armor',
'Lilium Armor',
'Titan Armor',
'Brave Armor',
'Destroy Armor',
'Phantom Armor',
'Seraphim Armor',
'Divine Armor',
'Kings Armor',
'Hades Armor',
'Queen Armor',



]


# Armor's Item End