
BootsList = [
'Bronze Boots',
'Dragon Boots',
'Pad Boots',
'Legendary Boots',
'Bone Boots',
'Leather Boots',
'Scale Boots',
'Sphinx Boots',
'Brass Boots',
'Plate Boots',
'Vine Boots',
'Silk Boots',
'Wind Boots',
'Spirit Boots',
'Guardian Boots',
'Storm Crow Boots',
'Black Dragon Boots',
'Dark Phoenix Boots',
'Grand Sould Boots',
'HolySpirit Boots',
'Thunder Boots',
'Great Dragon Boots',
'Black Soul Boots',
'Hurricane Boots',
'Red Spirit Boots',
'Round Boots',
'Adamantine Boots',
'Dark Steel Boots',
'Dark Master Boots',
'Dragon Knight Boots',
'Venomist Boots',
'Sylpid Ray Boots',
'Volcano Boots',
'Sunlight Boots',
'Ashcrow Boots',
'Eclipse Boots',
'Iris Boots',
'Valiant Boots',
'Glorious Boots',
'Mistery Boots',
'Red wing Boots',
'Ancient Boots',
'Black Rose Boots',
'Aura Boots',
'Lilium Boots',
'Titan Boots',
'Brave Boots',
'Destroy Boots',
'Phantom Boots',
'Seraphim Boots',
'Divine Boots',
'Kings Boots',
'Hades Boots',
'Queen Boots',



]


# Boots's Item End