
GlovesList = [
'Bronze Gloves',
'Dragon Gloves',
'Pad Gloves',
'Legendary Gloves',
'Bone Gloves',
'Leather Gloves',
'Scale Gloves',
'Sphinx Gloves',
'Brass Gloves',
'Plate Gloves',
'Vine Gloves',
'Silk Gloves',
'Wind Gloves',
'Spirit Gloves',
'Guardian Gloves',
'Storm Crow Gloves',
'Black Dragon Gloves',
'Dark Phoenix Gloves',
'Grand Sould Gloves',
'HolySpirit Gloves',
'Thunder Gloves',
'Great Dragon Gloves',
'Black Soul Gloves',
'Hurricane Gloves',
'Red Spirit Gloves',
'Round Gloves',
'Adamantine Gloves',
'Dark Steel Gloves',
'Dark Master Gloves',
'Dragon Knight Gloves',
'Venomist Gloves',
'Sylpid Ray Gloves',
'Volcano Gloves',
'Sunlight Gloves',
'Ashcrow Gloves',
'Eclipse Gloves',
'Iris Gloves',
'Valiant Gloves',
'Glorious Gloves',
'Mistery Gloves',
'Red wing Gloves',
'Ancient Gloves',
'Black Rose Gloves',
'Aura Gloves',
'Lilium Gloves',
'Titan Gloves',
'Brave Gloves',
'Destroy Gloves',
'Phantom Gloves',
'Seraphim Gloves',
'Divine Gloves',
'Kings Gloves',
'Hades Gloves',
'Queen Gloves',



]


# Gloves's Item End