
helmList = [
'Bronze Helm',
'Dragon Helm',
'Pad Helm',
'Legendary Helm',
'Bone Helm',
'Leather Helm',
'Scale Helm',
'Sphinx Helm',
'Brass Helm',
'Plate Helm',
'Vine Helm',
'Silk Helm',
'Wind Helm',
'Spirit Helm',
'Guardian Helm',
'Storm Crow Helm',
'Black Dragon Helm',
'Dark Phoenix Helm',
'Grand Sould Helm',
'HolySpirit Helm',
'Thunder Helm',
'Great Dragon Helm',
'Black Soul Helm',
'Hurricane Helm',
'Red Spirit Helm',
'Round Helm',
'Adamantine Helm',
'Dark Steel Helm',
'Dark Master Helm',
'Dragon Knight Helm',
'Venomist Helm',
'Sylpid Ray Helm',
'Volcano Helm',
'Sunlight Helm',
'Ashcrow Helm',
'Eclipse Helm',
'Iris Helm',
'Valiant Helm',
'Glorious Helm',
'Mistery Helm',
'Red wing Helm',
'Ancient Helm',
'Black Rose Helm',
'Aura Helm',
'Lilium Helm',
'Titan Helm',
'Brave Helm',
'Destroy Helm',
'Phantom Helm',
'Seraphim Helm',
'Divine Helm',
'Kings Helm',
'Hades Helm',
'Queen Helm',



]


# Helm's Item End