
PantsList = [
'Bronze Pants',
'Dragon Pants',
'Pad Pants',
'Legendary Pants',
'Bone Pants',
'Leather Pants',
'Scale Pants',
'Sphinx Pants',
'Brass Pants',
'Plate Pants',
'Vine Pants',
'Silk Pants',
'Wind Pants',
'Spirit Pants',
'Guardian Pants',
'Storm Crow Pants',
'Black Dragon Pants',
'Dark Phoenix Pants',
'Grand Sould Pants',
'HolySpirit Pants',
'Thunder Pants',
'Great Dragon Pants',
'Black Soul Pants',
'Hurricane Pants',
'Red Spirit Pants',
'Round Pants',
'Adamantine Pants',
'Dark Steel Pants',
'Dark Master Pants',
'Dragon Knight Pants',
'Venomist Pants',
'Sylpid Ray Pants',
'Volcano Pants',
'Sunlight Pants',
'Ashcrow Pants',
'Eclipse Pants',
'Iris Pants',
'Valiant Pants',
'Glorious Pants',
'Mistery Pants',
'Red wing Pants',
'Ancient Pants',
'Black Rose Pants',
'Aura Pants',
'Lilium Pants',
'Titan Pants',
'Brave Pants',
'Destroy Pants',
'Phantom Pants',
'Seraphim Pants',
'Divine Pants',
'Kings Pants',
'Hades Pants',
'Queen Pants',



]


# Pants's Item End